- name: variables to print #space after colon is mandatory  
  hosts: web
  vars: #play level, all tasks in this play have access to this
    COURSE: "DevOps with AWS"
    DURATION: "120HRS"
    TRAINER: "Sivakumar Reddy "
    Student: "Venkatesulu"
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}, Student: {{Student}}"

  tasks:
  - name: print the information again
    vars: #Task level variables
      Course: "Ansible"
    Duration: "Two Weeks"
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}, Student: {{Student}}"
  
  tasks: # this will take main variables
  - name: print the information again and again
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}, Student: {{Student}}"