- name: variable from prompt
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: Please enter the course name
  - name: TRAINER
    prompt: Please enter the trainer name
  - name: DURATION
    prompt: Please enter the duration
  - name: STUDENT
    prompt: Please enter the student name
  tasks:
  ansible.builtin.debug:
    msg: "Hi, I am learning {{COURSE}}, Trainer: {{TRAINER}}, duration of the course: {{DURATION}}, Student name: {{STUDENT}}"