- name: variable to print
  hosts: web
  vars:
    COURSE: "DevOps with AWS from Play level"
    DURATION: "120HRS"
    TRAINER: "Sivakumar Reddy "
    Student: "Venkatesulu"
  vars_prompt:
  - name: COURSE
    prompt: Please enter the course name
    private: false # not confidential
  - name: TRAINER
    prompt: Please enter the trainer name
    private: false # not confidential
  - name: DURATION
    prompt: Please enter the duration
    private: false # not confidential
  - name: STUDENT
    prompt: Please enter the student name
    private: false # not confidential
  tasks:
  - name: print the information
    vars:
      COURSE: "DevOps with AWS from Task level"
      DURATION: "120HRS"
      TRAINER: "Sivakumar Reddy "
      Student: "Venkatesulu"
    ansibale.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, Duration is: {{DURATION}}, TRAINER is: {{TRAINER}}, Student is{{STUDENT}}"