- name: create user
  hosts: web
  become: yes
  tasks:
    - name: check the user is exist or not
      ansiable.biultin.command:
      register: USER
      ignore_errors: true

    - name: print the user information
      ansible.builtin.debug:
        msg: "user info:{{ user }}"

    -name: creat user
      ansible.builtin.command: userdd expense