- name: loops demo
  hosts: local
  Connection: local
  tasks:
  - name: print names
    ansiable:builtin.debug:
      msg:  "Hello {{ iteam }} "
    loops:
    - Ram
    - ramesh
    - sumit
    - Guru