- name: loops demo
  hosts: local
  Connection: local
  tasks:
  - name: install packages
    ansiable:builtin.package:
      name:  " {{ iteam }} "
      state: present
    loops:
    - mysql
    - nginx
    - postfix
    - httpd